apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fluence
resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml
  - deployment.yml
  - service.yml
  - httproute.yml

configMapGenerator:
  - name: api-config
    envs:
      - config.env
